add_note:
  name: Add Note
  description: Add a new voice note
  fields:
    content:
      name: Content
      description: The content of the note
      required: true
      selector:
        text:
          multiline: true

complete_note:
  name: Complete Note
  description: Mark a note as completed
  fields:
    note_id:
      name: Note ID
      description: The ID of the note to complete
      required: true
      selector:
        text:

delete_note:
  name: Delete Note
  description: Delete a note
  fields:
    note_id:
      name: Note ID
      description: The ID of the note to delete
      required: true
      selector:
        text: